version: "3.9"

services:
  app:
    build:
      dockerfile: ./docker/Dockerfile
    shm_size: 2gb
    volumes:
      - ./scrap.py:/scrap.py
      - ./screenshots:/screenshots:cached
    command: 'python3 scrap.py'
    